# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumno')),
                ('archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Archivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='localizacion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='localizacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='localizacion',
            name='lugar',
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
