# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_auto_20161125_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
