# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_auto_20161126_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajon',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cajon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Cajon'),
        ),
    ]
