# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alumnos', '0004_auto_20161201_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumno')),
                ('desde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_desde', to='Alumnos.Cajon')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_hasta', to='Alumnos.Cajon')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
