# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='apellido',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nombre',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nombre_usuario',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rol',
            field=models.CharField(choices=[('JAD', 'Jefe de Auxiliares'), ('AD', 'Auxiliar Docente')], default='AD', max_length=3),
        ),
    ]
