# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='usuario',
        ),
    ]
